apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: rhdh
  namespace: rhdh
spec:
  application:
    appConfig:
      configMaps:
        - name: rhdh-app-config
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: rhdh-secrets
  database:
    enableLocalDb: false