apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres/service.yaml
- postgres/statefulset.yaml
- gitea/deployment.yaml
- gitea/service.yaml
- gitea/route.yaml
- gitea/pvc.yaml
