apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ossm-subscription.yaml
- kiali-subscription.yaml
- otel-subscription.yaml
- tempo-subscription.yaml
- keycloak-operatorgroup.yaml
- keycloak-sub.yaml
- rhdh-og.yaml
- rhdh-subscription.yaml