apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: productpage-jwt
  namespace: bookinfo
spec:
  targetRefs:
  - kind: Service
    group: ""
    name: productpage
  jwtRules:
  - issuer: "https://keycloak.apps.snoaxolab.axodevelopment.dev/realms/workshop"
    jwksUri: "https://keycloak.apps.snoaxolab.axodevelopment.dev/realms/workshop/protocol/openid-connect/certs"
    audiences:
    - bookinfo
    forwardOriginalToken: true
---
# TODO: I don't think deny is required directly
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: productpage-deny-unauthenticated
  namespace: bookinfo
spec:
  targetRefs:
  - kind: Service
    group: ""
    name: productpage
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]