apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: openshift-gitops
  labels:
    component: service-mesh
    dependency: observability
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/axodevelopment/workshop-ossm
    targetRevision: main
    path: infra/apps/kiali
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: kiali.io
    kind: Kiali
    jsonPointers:
    - /status