apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ossm-3-2
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/axodevelopment/workshop-ossm
    targetRevision: main
    path: infra/apps/ossm/3.2
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: sailoperator.io
    kind: Istio
    jsonPointers:
    - /status
  - group: sailoperator.io
    kind: IstioCNI
    jsonPointers:
    - /status
  - group: sailoperator.io
    kind: ZTunnel
    jsonPointers:
    - /status