apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-core
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/axodevelopment/workshop-ossm
    targetRevision: main
    path: infra/core
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true