apiVersion: v1
kind: Namespace
metadata:
  name: tempo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    openshift.io/user-monitoring: "true"

# Ztunnel doesn't seem to work well because of mtls, maybe i need to 
# do this connectivity only with side car?
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: tempo
#  annotations:
#    argocd.argoproj.io/sync-wave: "-2"
#  labels:
#    openshift.io/user-monitoring: "true"
#    istio.io/dataplane-mode: ambient
#    istio-discovery: enabled