apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ws-bookinfo-1-0-dep
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    component: service-mesh
    dependency: observability
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: workshop # TODO: move to workshop-*
  source:
    repoURL: https://github.com/axodevelopment/workshop-ossm
    targetRevision: main
    path: workshop/bookinfo/1.0/dependencies
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true