apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  GITEA__server__DOMAIN: "gitea.apps.snoaxolab.axodevelopment.dev"
  GITEA__server__ROOT_URL: "https://gitea.apps.snoaxolab.axodevelopment.dev/"
  GITEA__server__HTTP_PORT: "3000"
  GITEA__server__START_SSH_SERVER: "false"
  GITEA__server__LFS_START_SERVER: "true"
  GITEA__database__DB_TYPE: "postgres"
  GITEA__database__HOST: "gitea-postgresql.gitea.svc.cluster.local:5432"
  GITEA__database__NAME: "gitea"
  GITEA__database__USER: "gitea"
  GITEA__database__SSL_MODE: "disable"
  GITEA__repository__ROOT: "/data/gitea/repositories"
  GITEA__security__INSTALL_LOCK: "true"
  GITEA__security__PASSWORD_COMPLEXITY: "off"
  GITEA__service__DISABLE_REGISTRATION: "false"
  GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
  GITEA__service__REGISTER_EMAIL_CONFIRM: "false"
  GITEA__service__ENABLE_NOTIFY_MAIL: "false"
  GITEA__mailer__ENABLED: "false"
  GITEA__cache__ADAPTER: "memory"
  GITEA__session__PROVIDER: "memory"
  GITEA__log__MODE: "console"
  GITEA__log__LEVEL: "info"
  GITEA__webhook__ALLOWED_HOST_LIST: "*"
  GITEA__APP_NAME: "Gitea - snoaxolab Workshop"
  GITEA__indexer__ISSUE_INDEXER_TYPE: "bleve"
  GITEA__indexer__REPO_INDEXER_ENABLED: "true"