apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgres-secret
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
type: Opaque
stringData:
  POSTGRES_USER: gitea
  POSTGRES_PASSWORD: gitea
  POSTGRES_DB: gitea