apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  GITEA_ADMIN_USER: "gitea-admin"
  GITEA_ADMIN_PASSWORD: "123456-gitea-admin-password"
  GITEA_ADMIN_EMAIL: "admin@gitea.apps.snoaxolab.axodevelopment.dev"
