apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sa.yaml
- crb.yaml
- telemetry.yaml
- servicemonitor.yaml
- zt-podmonitor.yaml
- istio-proxies-monitor.yaml

# since most of this is istio i should consier moving it into 3.2